---
- name: Define php_fpm_daemon.
  set_fact:
    php_fpm_daemon: "{{ __php_fpm_daemon }}"
  when: php_fpm_daemon is not defined

- name: Define php_fpm_pool_conf_path.
  set_fact:
    php_fpm_pool_conf_path: "{{ __php_fpm_pool_conf_path }}"
  when: php_fpm_pool_conf_path is not defined

- name: Define php_fpm_pool_user.
  set_fact:
    php_fpm_pool_user: "{{ __php_fpm_pool_user }}"
  when: php_fpm_pool_user is not defined

- name: Define php_fpm_pool_group.
  set_fact:
    php_fpm_pool_group: "{{ __php_fpm_pool_group }}"
  when: php_fpm_pool_group is not defined

- name: Stat php_fpm_pool_conf_path
  stat:
    path: "{{ php_fpm_pool_conf_path | dirname }}"
  register: php_fpm_pool_conf_path_dir_stat

- name: Ensure the default pool directory exists.
  file:
    path: "{{ php_fpm_pool_conf_path | dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: php_fpm_pool_conf_path_dir_stat.stat.islnk is not defined

- name: Ensure the default pool exists.
  template:
    src: www.conf.j2
    dest: "{{ php_fpm_pool_conf_path }}"
    owner: root
    group: root
    mode: 0644
    force: yes
  when: php_enable_php_fpm
  notify: restart php-fpm

- name: Ensure php-fpm is started and enabled at boot (if configured).
  service:
    name: "{{ php_fpm_daemon }}"
    state: started
    enabled: yes
  when: php_enable_php_fpm and ansible_distribution != "Debian"

# See: https://github.com/ansible/ansible/issues/22303
- name: Ensure php-fpm is started and enabled at boot (if configured, Debian).
  service:
    name: "{{ php_fpm_daemon }}"
    state: started
    enabled: yes
    use: service
  when: php_enable_php_fpm and ansible_distribution == "Debian"
